version: '3.8'
services:
  multitenant-app:
    image: multitenant-app:latest
    build:
      context: ./MultiTenant
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "8086:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
      - keycloak 
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "2433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - app-network

  keycloak-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpass
    ports:
      - "5432:5432"
    volumes:
      - keycloakdbdata:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpass
      - KC_LOG_LEVEL=DEBUG 
      - KC_HOSTNAME=keycloak.local
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT=true
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command: start-dev
    networks:
      app-network: 
          aliases:
            - keycloak.local

volumes:
  sqlserverdata:
  keycloakdbdata:
networks:
  app-network:
    driver: bridge
